### ISSUE TITLE
[ISSUE][LOGIN] Desalineación del botón "Volver al inicio"

### ISSUE THREAD

**Issue by EdsonLozaT34** [GitHubX69/PROYECTO-SISTEMAS#7]
En la pantalla de login, el botón "Volver al inicio" aparece desalineado en comparación con los otros elementos de la interfaz. Esto afecta la consistencia visual y la experiencia de usuario en esta sección de la aplicación.
Pasos para reproducir el problema:

Acceder a la pantalla de login del sistema.
Observar la posición y alineación del botón "Volver al inicio" respecto a los otros elementos.
Notar que el botón no está alineado adecuadamente, lo que genera una presentación visual desigual.
![image](https://github.com/user-attachments/assets/657f8893-401f-4614-abe8-e4c1516c33e4)

**Comment by GitHubX69** [comment]
"""
Antes de ejecutar el test, ejecutar el siguiente comando para instalar la
libreria necesaria

pip install selenium webdriver-manager
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

# Configuración automática del WebDriver
driver = webdriver.Chrome()

# Maximizar la ventana del navegador
driver.maximize_window()


# Abrir url en el navegador
driver.get('https://www.multicine.com.bo/register')


# Acciones para interactuar con el navegador
driver.find_element(By.XPATH, ***@***.***='firstname']").send_keys("PANA"
)
driver.find_element(By.XPATH, ***@***.***='lastname']").send_keys(
"WISTON")
driver.find_element(By.XPATH, ***@***.***='phone']").send_keys(
"1234567890")
driver.find_element(By.XPATH, ***@***.***='address']").send_keys("Tu
Dirección Aquí")
driver.find_element(By.ID, "ion-sel-1").click()
time.sleep(1)
driver.find_element(By.XPATH, "//div[contains(text(), 'La
Paz')]//ancestor::button").click()
driver.find_element(By.XPATH, ***@***.***='docextend']").send_keys("Tu
Texto Aquí")
driver.find_element(By.XPATH, ***@***.***='docid']").send_keys("Tu ID
Aquí")
driver.find_element(By.XPATH, ***@***.***='email']").send_keys("
***@***.***")
driver.find_element(By.XPATH, ***@***.***='emailConfirm']").send_keys("
***@***.***")
driver.find_element(By.XPATH, ***@***.***='password']").send_keys(
"TuContraseñaSegura")
driver.find_element(By.XPATH, ***@***.***='passwordConfirm']").send_keys(
"TuContraseñaSegura")
checkbox = driver.find_element(By.ID, "ion-cb-0")
if not checkbox.is_selected():
    checkbox.click()

time.sleep(1)

# Intentar hacer clic en el botón "REGISTRAR"
register_button = driver.find_element(By.XPATH, "//ion-button[contains(text(),
'REGISTRAR')]")

# Verificar si el botón está habilitado
if not register_button.get_attribute("disabled"):
    register_button.click()
else:
    print("El botón 'REGISTRAR' está deshabilitado.")

driver.quit()

print("Prueba visual completada")

**Comment by GitHubX69** [comment]
"""
Antes de ejecutar el test, ejecutar el siguiente comando para instalar la
libreria necesaria

pip install selenium webdriver-manager
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

# Configuración automática del WebDriver
driver = webdriver.Chrome()

# Maximizar la ventana del navegador
driver.maximize_window()

# Abrir url en el navegador
driver.get('https://www.multicine.com.bo/register')

# Acciones para interactuar con el navegador
time.sleep(2)
driver.find_element(By.XPATH, ***@***.***='ion-sel-1']").click()


time.sleep(2)
driver.find_element(By.XPATH, ***@***.***='firstname']").send_keys("PANA"
)
time.sleep(2)
driver.find_element(By.XPATH, ***@***.***='lastname']").send_keys(
"WISTON")
time.sleep(2)
driver.find_element(By.XPATH, ***@***.***='phone']").send_keys(
"1234567890")
time.sleep(2)
driver.find_element(By.XPATH, ***@***.***='address']").send_keys("Tu
Dirección Aquí")
time.sleep(2)

# Hacer clic en el botón de selección de ciudad
driver.find_element(By.XPATH, ***@***.***='ion-sel-1']").click()
time.sleep(1)

# Seleccionar "LA PAZ" con el nuevo ID
driver.find_element(By.XPATH, ***@***.***='alert-input-3-0' and
contains(., 'LA PAZ')]").click()

driver.find_element(By.XPATH, ***@***.***='docextend']").send_keys("Tu
Texto Aquí")
driver.find_element(By.XPATH, ***@***.***='docid']").send_keys("Tu ID
Aquí")
driver.find_element(By.XPATH, ***@***.***='email']").send_keys("
***@***.***")
driver.find_element(By.XPATH, ***@***.***='emailConfirm']").send_keys("
***@***.***")
driver.find_element(By.XPATH, ***@***.***='password']").send_keys(
"TuContraseñaSegura")
driver.find_element(By.XPATH, ***@***.***='passwordConfirm']").send_keys(
"TuContraseñaSegura")

checkbox = driver.find_element(By.ID, "ion-cb-0")
if not checkbox.is_selected():
    checkbox.click()

time.sleep(1)

# Intentar hacer clic en el botón "REGISTRAR"
register_button = driver.find_element(By.XPATH, "//ion-button[contains(text(),
'REGISTRAR')]")

# Verificar si el botón está habilitado
if not register_button.get_attribute("disabled"):
    register_button.click()
else:
    print("El botón 'REGISTRAR' está deshabilitado.")

driver.quit()

print("Prueba visual completada")

**Comment by GitHubX69** [comment]
"""
Antes de ejecutar el test, ejecutar el siguiente comando para instalar la
libreria necesaria

pip install selenium webdriver-manager
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time

# Configuración automática del WebDriver
driver = webdriver.Chrome()

# Maximizar la ventana del navegador
driver.maximize_window()

# Abrir url en el navegador
driver.get('https://wordledehoy.com/')

time.sleep(2)
# Acciones para interactuar con el navegador
driver.find_element(By.XPATH, "//span[text()='Nuevo']//parent::div").click()
time.sleep(2)

driver.find_element(By.XPATH, ***@***.*** = 'reveal-button']").click()
time.sleep(2)

solution = driver.find_element(By.XPATH, ***@***.***='solution-word']").text

solution = solution.lower()
print(f"LA SOLUCION ES:{solution}")
#time.sleep(3)

# Abrir url en el navegador
driver.get('https://lapalabradeldia.com/')

for letra in solution:

    print(letra)
    driver.find_element(By.XPATH, ***@***.*** = '{letra}']").
click()

    time.sleep(4)

    driver.find_element(By.XPATH, ***@***.*** = 'procesar
palabra']").click()

time.sleep(3)


driver.quit()



print("Prueba visual completada")

**Comment by GitHubX69** [comment]
"""
Antes de ejecutar el test, ejecutar los siguientes comandos para instalar
las librerias necesarias

pip install selenium webdriver-manager
pip install eyes-selenium

"""
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from applitools.selenium import Eyes, Target

# Applitools - Configura tu API Key
APPLITOOLS_API_KEY =
'HixEn102VlRlNU7RoxZzyN102npxk0108jpsXXH4lBS1041oYDc110'

# Inicializar Applitools Eyes
eyes = Eyes()
eyes.api_key = APPLITOOLS_API_KEY

# Configuración automática del WebDriver sin usar Service
driver = webdriver.Chrome(ChromeDriverManager().install())

# Maximizar la ventana del navegador
driver.maximize_window()

try:
    # Empezar una sesión de prueba visual con Applitools
    eyes.open(driver=driver, app_name='Demo App', test_name='Prueba Visual
con Applitools')

    # Navegar a la página que queremos probar
    driver.get('https://demo.applitools.com')

    # Tomar una captura de pantalla completa de la página
    eyes.check("Página completa", Target.window().fully())

    # Simulación de una interacción: Rellenar campos de formulario y hacer
clic en "Log In"
    driver.find_element(By.ID, "username").send_keys("admin")
    driver.find_element(By.ID, "password").send_keys("password")
    driver.find_element(By.ID, "log-in").click()

    # Tomar una captura de pantalla después de la interacción
    eyes.check("Después del Login", Target.window().fully())

    # Cerrar los ojos de Applitools y finalizar la prueba
    eyes.close()

finally:
    # Finalizar la sesión de Selenium y Applitools
    driver.quit()
    eyes.abort_if_not_closed()

print("Prueba visual completada")

**Comment by GitHubX69** [comment]
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

# Configuración del webdriver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.maximize_window()

# Acceder a Google
driver.get('https://www.google.com/')
time.sleep(2)

# Buscar "fecha de hoy"
search_box = driver.find_element(By.NAME, 'q')
search_box.send_keys('fecha de hoy')
search_box.submit()
time.sleep(3)

# Obtener el resultado de la fecha
resultado = driver.find_element(By.XPATH, ***@***.***='vk_bk dDoNo
FzvWSb']").text
print(f"Fecha de hoy: {resultado}")

# Almacenar la fecha en una variable
fecha_hoy = resultado

# Esperar un momento antes de ir a Wikipedia
time.sleep(2)

# Acceder a Wikipedia
driver.get('https://www.wikipedia.org/')
time.sleep(3)

# Buscar la fecha en Wikipedia
search_box_wiki = driver.find_element(By.ID, 'searchInput')
search_box_wiki.send_keys(fecha_hoy)
search_box_wiki.submit()

# Capturar el texto "Resultados de la búsqueda"
resultados_heading = driver.find_element(By.XPATH,
***@***.***='firstHeading']").text

# Almacenar el texto de resultados en una variable
texto_resultados = resultados_heading

# Mostrar la variable en consola
print(f"Texto de resultados: {texto_resultados}")

# Esperar un momento antes de cerrar el navegador
time.sleep(10)

print("uwu")
# Cerrar el navegador
driver.quit()
